name: intermetallics-bulk-modulus-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - pymatgen
      - matminer
      - mp-api==0.46.1
      - emmet-core==0.86.4
      - python-dotenv
